// src/routes/(app)/profile/+page.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { goto } from '$app/navigation';
	import { user } from '$lib/stores';
	import { getUserProfile, updateUserProfile, type UserProfile, type UserStats } from '$lib/apis/user-management';
	
	let userProfile: UserProfile | null = null;
	let userStats: UserStats | null = null;
	let loading = true;
	let error = '';
	let editing = false;
	
	// Edit form
	let editForm = {
		username: '',
		full_name: '',
		bio: ''
	};
	
	onMount(async () => {
		await loadProfile();
	});
	
	async function loadProfile() {
		loading = true;
		try {
			const token = localStorage.getItem('token');
			if (!token) {
				goto('/');
				return;
			}
			
			const data = await getUserProfile(token);
			userProfile = data.user;
			userStats = data.stats;
			
			// Populate edit form
			editForm = {
				username: userProfile.username || '',
				full_name: userProfile.full_name || '',
				bio: userProfile.bio || ''
			};
		} catch (e: any) {
			error = e.message;
			console.error('Error loading profile:', e);
		} finally {
			loading = false;
		}
	}
	
	async function saveProfile() {
		try {
			const token = localStorage.getItem('token');
			if (!token) return;
			
			await updateUserProfile(token, editForm);
			await loadProfile();
			editing = false;
		} catch (e: any) {
			error = e.message;
		}
	}
	
	function formatDate(dateString: string): string {
		return new Date(dateString).toLocaleDateString('en-US', {
			year: 'numeric',
			month: 'long',
			day: 'numeric'
		});
	}
	
	function formatCurrency(amount: number): string {
		return new Intl.NumberFormat('en-US', {
			style: 'currency',
			currency: 'USD'
		}).format(amount);
	}
</script>

<svelte:head>
	<title>My Profile - TradeBerg</title>
</svelte:head>

<div class="max-w-5xl mx-auto p-6">
	<h1 class="text-3xl font-bold mb-6">My Profile</h1>
	
	{#if loading}
		<div class="text-center py-12">
			<div class="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-600 mx-auto"></div>
			<p class="mt-4 text-gray-600 dark:text-gray-400">Loading profile...</p>
		</div>
	{:else if error}
		<div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded">
			{error}
		</div>
	{:else if userProfile}
		<div class="grid grid-cols-1 lg:grid-cols-3 gap-6">
			<!-- Profile Card -->
			<div class="lg:col-span-1">
				<div class="bg-white dark:bg-gray-800 rounded-lg shadow p-6">
					<div class="text-center">
						{#if userProfile.avatar_url}
							<img src={userProfile.avatar_url} alt="Avatar" class="w-24 h-24 rounded-full mx-auto mb-4" />
						{:else}
							<div class="w-24 h-24 rounded-full bg-blue-600 flex items-center justify-center text-white text-3xl font-bold mx-auto mb-4">
								{userProfile.email?.[0]?.toUpperCase() || 'U'}
							</div>
						{/if}
						
						<h2 class="text-xl font-bold">{userProfile.full_name || userProfile.username || 'User'}</h2>
						<p class="text-sm text-gray-500 dark:text-gray-400">{userProfile.email}</p>
						
						{#if userProfile.subscription_tier !== 'free'}
							<span class="inline-block mt-2 px-3 py-1 bg-purple-100 dark:bg-purple-900 text-purple-800 dark:text-purple-200 text-sm rounded-full font-medium">
								{userProfile.subscription_tier.toUpperCase()}
							</span>
						{/if}
						
						<div class="mt-4 pt-4 border-t border-gray-200 dark:border-gray-700">
							<div class="text-sm text-gray-600 dark:text-gray-400">
								Member since {formatDate(userProfile.created_at)}
							</div>
						</div>
					</div>
				</div>
				
				<!-- Credits Card -->
				<div class="bg-white dark:bg-gray-800 rounded-lg shadow p-6 mt-6">
					<h3 class="text-lg font-bold mb-4">Credits</h3>
					<div class="text-center">
						<div class="text-4xl font-bold text-blue-600 dark:text-blue-400">
							{userProfile.credits}
						</div>
						<div class="text-sm text-gray-500 dark:text-gray-400 mt-1">Available Credits</div>
					</div>
					
					<button
						on:click={() => goto('/credits')}
						class="w-full mt-4 px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition"
					>
						Buy More Credits
					</button>
				</div>
			</div>
			
			<!-- Details Section -->
			<div class="lg:col-span-2 space-y-6">
				<!-- Profile Information -->
				<div class="bg-white dark:bg-gray-800 rounded-lg shadow p-6">
					<div class="flex justify-between items-center mb-4">
						<h3 class="text-lg font-bold">Profile Information</h3>
						{#if !editing}
							<button
								on:click={() => editing = true}
								class="px-4 py-2 text-sm bg-gray-100 dark:bg-gray-700 rounded-lg hover:bg-gray-200 dark:hover:bg-gray-600"
							>
								Edit Profile
							</button>
						{/if}
					</div>
					
					{#if editing}
						<div class="space-y-4">
							<div>
								<label class="block text-sm font-medium mb-1">Username</label>
								<input
									type="text"
									bind:value={editForm.username}
									class="w-full px-4 py-2 border rounded-lg dark:bg-gray-700 dark:border-gray-600"
									placeholder="Enter username"
								/>
							</div>
							
							<div>
								<label class="block text-sm font-medium mb-1">Full Name</label>
								<input
									type="text"
									bind:value={editForm.full_name}
									class="w-full px-4 py-2 border rounded-lg dark:bg-gray-700 dark:border-gray-600"
									placeholder="Enter full name"
								/>
							</div>
							
							<div>
								<label class="block text-sm font-medium mb-1">Bio</label>
								<textarea
									bind:value={editForm.bio}
									rows="3"
									class="w-full px-4 py-2 border rounded-lg dark:bg-gray-700 dark:border-gray-600"
									placeholder="Tell us about yourself"
								></textarea>
							</div>
							
							<div class="flex gap-2">
								<button
									on:click={saveProfile}
									class="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700"
								>
									Save Changes
								</button>
								<button
									on:click={() => editing = false}
									class="px-4 py-2 bg-gray-200 dark:bg-gray-700 rounded-lg hover:bg-gray-300 dark:hover:bg-gray-600"
								>
									Cancel
								</button>
							</div>
						</div>
					{:else}
						<div class="space-y-3">
							<div>
								<div class="text-sm text-gray-500 dark:text-gray-400">Username</div>
								<div class="font-medium">{userProfile.username || 'Not set'}</div>
							</div>
							<div>
								<div class="text-sm text-gray-500 dark:text-gray-400">Full Name</div>
								<div class="font-medium">{userProfile.full_name || 'Not set'}</div>
							</div>
							<div>
								<div class="text-sm text-gray-500 dark:text-gray-400">Email</div>
								<div class="font-medium">{userProfile.email}</div>
							</div>
							{#if userProfile.bio}
								<div>
									<div class="text-sm text-gray-500 dark:text-gray-400">Bio</div>
									<div class="font-medium">{userProfile.bio}</div>
								</div>
							{/if}
						</div>
					{/if}
				</div>
				
				<!-- Statistics -->
				{#if userStats}
					<div class="bg-white dark:bg-gray-800 rounded-lg shadow p-6">
						<h3 class="text-lg font-bold mb-4">Statistics</h3>
						
						<div class="grid grid-cols-2 md:grid-cols-3 gap-4">
							<div class="text-center p-4 bg-gray-50 dark:bg-gray-900 rounded-lg">
								<div class="text-2xl font-bold text-blue-600 dark:text-blue-400">
									{userStats.total_credits_purchased}
								</div>
								<div class="text-sm text-gray-500 dark:text-gray-400 mt-1">Credits Purchased</div>
							</div>
							
							<div class="text-center p-4 bg-gray-50 dark:bg-gray-900 rounded-lg">
								<div class="text-2xl font-bold text-green-600 dark:text-green-400">
									{userStats.total_credits_used}
								</div>
								<div class="text-sm text-gray-500 dark:text-gray-400 mt-1">Credits Used</div>
							</div>
							
							<div class="text-center p-4 bg-gray-50 dark:bg-gray-900 rounded-lg">
								<div class="text-2xl font-bold text-purple-600 dark:text-purple-400">
									{formatCurrency(userStats.total_spent)}
								</div>
								<div class="text-sm text-gray-500 dark:text-gray-400 mt-1">Total Spent</div>
							</div>
							
							<div class="text-center p-4 bg-gray-50 dark:bg-gray-900 rounded-lg">
								<div class="text-2xl font-bold text-orange-600 dark:text-orange-400">
									{userStats.total_payments}
								</div>
								<div class="text-sm text-gray-500 dark:text-gray-400 mt-1">Payments</div>
							</div>
							
							<div class="text-center p-4 bg-gray-50 dark:bg-gray-900 rounded-lg">
								<div class="text-2xl font-bold text-teal-600 dark:text-teal-400">
									{userStats.api_calls_count}
								</div>
								<div class="text-sm text-gray-500 dark:text-gray-400 mt-1">API Calls</div>
							</div>
							
							<div class="text-center p-4 bg-gray-50 dark:bg-gray-900 rounded-lg">
								<div class="text-2xl font-bold text-pink-600 dark:text-pink-400">
									{userStats.login_count}
								</div>
								<div class="text-sm text-gray-500 dark:text-gray-400 mt-1">Logins</div>
							</div>
						</div>
					</div>
				{/if}
				
				<!-- Quick Actions -->
				<div class="bg-white dark:bg-gray-800 rounded-lg shadow p-6">
					<h3 class="text-lg font-bold mb-4">Quick Actions</h3>
					
					<div class="grid grid-cols-1 md:grid-cols-2 gap-4">
						<button
							on:click={() => goto('/credits')}
							class="p-4 border-2 border-blue-600 text-blue-600 rounded-lg hover:bg-blue-50 dark:hover:bg-blue-900/20 transition text-left"
						>
							<div class="font-bold">Buy Credits</div>
							<div class="text-sm mt-1">Purchase more credits</div>
						</button>
						
						<button
							on:click={() => goto('/transactions')}
							class="p-4 border-2 border-gray-300 dark:border-gray-600 rounded-lg hover:bg-gray-50 dark:hover:bg-gray-700 transition text-left"
						>
							<div class="font-bold">View Transactions</div>
							<div class="text-sm mt-1">See your credit history</div>
						</button>
						
						<button
							on:click={() => goto('/payments')}
							class="p-4 border-2 border-gray-300 dark:border-gray-600 rounded-lg hover:bg-gray-50 dark:hover:bg-gray-700 transition text-left"
						>
							<div class="font-bold">Payment History</div>
							<div class="text-sm mt-1">View all payments</div>
						</button>
						
						<button
							on:click={() => goto('/subscription')}
							class="p-4 border-2 border-gray-300 dark:border-gray-600 rounded-lg hover:bg-gray-50 dark:hover:bg-gray-700 transition text-left"
						>
							<div class="font-bold">Subscription</div>
							<div class="text-sm mt-1">Manage your plan</div>
						</button>
					</div>
				</div>
			</div>
		</div>
	{/if}
</div>

// frontend/src/app/profile/page.tsx
"use client";

import React, { useState, useEffect } from "react";
import { useUser } from "@/contexts/UserContext";
import Image from "next/image";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea-fix";
import { Separator } from "@/components/ui/separator";
import { useRouter } from "next/navigation";

export default function ProfilePage() {
  const { user, profile, isLoading, isAuthenticated, updateProfile } = useUser();
  const router = useRouter();
  
  const [formData, setFormData] = useState({
    full_name: "",
    bio: "",
    country: "",
    phone: "",
  });
  const [isEditing, setIsEditing] = useState(false);
  const [isSaving, setIsSaving] = useState(false);

  // Redirect if not authenticated
  useEffect(() => {
    if (!isLoading && !isAuthenticated) {
      router.push("/login");
    }
  }, [isLoading, isAuthenticated, router]);

  // Update form data when profile loads
  useEffect(() => {
    if (profile) {
      setFormData({
        full_name: profile.full_name || "",
        bio: profile.bio || "",
        country: profile.country || "",
        phone: profile.phone || "",
      });
    }
  }, [profile]);

  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => {
    const { name, value } = e.target;
    setFormData((prev) => ({ ...prev, [name]: value }));
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsSaving(true);
    
    try {
      await updateProfile(formData);
      setIsEditing(false);
    } catch (error) {
      console.error("Error updating profile:", error);
    } finally {
      setIsSaving(false);
    }
  };

  if (isLoading) {
    return (
      <div className="flex items-center justify-center min-h-screen">
        <div className="animate-spin rounded-full h-12 w-12 border-t-2 border-b-2 border-primary"></div>
      </div>
    );
  }

  return (
    <div className="container max-w-4xl mx-auto px-4 py-8">
      <div className="bg-card rounded-xl shadow-lg p-6">
        {/* Debug Button */}
        <div className="mb-4 text-right">
          <Button 
            variant="outline" 
            size="sm"
            onClick={() => {
              console.log("Current User:", user);
              console.log("Current Profile:", profile);
              alert("Auth & Profile data logged to console. Please check developer tools.");
            }}
          >
            Debug User Info
          </Button>
        </div>
        
        <div className="flex flex-col md:flex-row items-center md:items-start gap-8">
          {/* Profile Avatar */}
          <div className="flex flex-col items-center">
            <div className="relative w-32 h-32 rounded-full overflow-hidden border-4 border-primary/20">
              {profile?.avatar_url ? (
                <Image
                  src={profile.avatar_url}
                  alt={profile.full_name || "User avatar"}
                  fill
                  className="object-cover"
                />
              ) : (
                <div className="w-full h-full flex items-center justify-center bg-gradient-to-br from-primary/30 to-primary/10 text-4xl font-bold text-primary">
                  {profile?.full_name?.charAt(0) || "U"}
                </div>
              )}
            </div>
            
            <div className="text-center mt-4">
              <div className="text-xs text-muted-foreground">Member since</div>
              <div>
                {profile?.created_at 
                  ? new Date(profile.created_at).toLocaleDateString("en-US", { year: "numeric", month: "long" })
                  : "Unknown"}
              </div>
            </div>
          </div>

          {/* Profile Info */}
          <div className="flex-1">
            {isEditing ? (
              <form onSubmit={handleSubmit} className="space-y-4">
                <div>
                  <label htmlFor="full_name" className="block text-sm font-medium mb-1">
                    Full Name
                  </label>
                  <Input
                    id="full_name"
                    name="full_name"
                    value={formData.full_name}
                    onChange={handleInputChange}
                    required
                  />
                </div>
                
                <div>
                  <label htmlFor="bio" className="block text-sm font-medium mb-1">
                    Bio
                  </label>
                  <Textarea
                    id="bio"
                    name="bio"
                    value={formData.bio}
                    onChange={handleInputChange}
                    rows={3}
                  />
                </div>
                
                <div>
                  <label htmlFor="country" className="block text-sm font-medium mb-1">
                    Country
                  </label>
                  <Input
                    id="country"
                    name="country"
                    value={formData.country}
                    onChange={handleInputChange}
                  />
                </div>
                
                <div>
                  <label htmlFor="phone" className="block text-sm font-medium mb-1">
                    Phone
                  </label>
                  <Input
                    id="phone"
                    name="phone"
                    type="tel"
                    value={formData.phone}
                    onChange={handleInputChange}
                    placeholder="+1 (123) 456-7890"
                  />
                </div>
                
                <div className="flex justify-end gap-2 pt-4">
                  <Button 
                    type="button" 
                    variant="outline" 
                    onClick={() => setIsEditing(false)}
                  >
                    Cancel
                  </Button>
                  <Button type="submit" disabled={isSaving}>
                    {isSaving ? "Saving..." : "Save Changes"}
                  </Button>
                </div>
              </form>
            ) : (
              <div>
                <div className="flex justify-between items-center">
                  <h1 className="text-2xl font-bold">{profile?.full_name}</h1>
                  <Button onClick={() => setIsEditing(true)}>Edit Profile</Button>
                </div>
                
                <div className="text-muted-foreground mb-4">{profile?.email}</div>
                
                <Separator className="my-4" />
                
                <div className="space-y-4">
                  {profile?.bio && (
                    <div>
                      <h3 className="text-sm font-medium text-muted-foreground">Bio</h3>
                      <p className="mt-1">{profile.bio}</p>
                    </div>
                  )}
                  
                  {profile?.country && (
                    <div>
                      <h3 className="text-sm font-medium text-muted-foreground">Country</h3>
                      <p className="mt-1">{profile.country}</p>
                    </div>
                  )}
                  
                  {profile?.phone && (
                    <div>
                      <h3 className="text-sm font-medium text-muted-foreground">Phone</h3>
                      <p className="mt-1">{profile.phone}</p>
                    </div>
                  )}
                  
                  {profile?.subscription_tier && (
                    <div>
                      <h3 className="text-sm font-medium text-muted-foreground">Subscription</h3>
                      <p className="mt-1 capitalize">{profile.subscription_tier}</p>
                    </div>
                  )}
                </div>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
